<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationsRepository extends EntityRepository
{
    public function getSetsRecords(){
        $qb = $this->createQueryBuilder('p');
        $qb->select('DISTINCT p.value');
        return $qb->getQuery()->getResult();
    }
}
